apiVersion: v1
kind: Service
metadata:
  name: aks-tfserving-text-classification
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8501
  selector:
    app: aks-tfserving-text-classification